local_costmap:
    map_topic: /map
    global_frame: /map
    robot_base_frame: /robot_{id}/base_link
    update_frequency: 1.0
    publish_frequency: 1.0
    static_map: false
    rolling_window: true
    width: 6.0
    height: 6.0
    resolution: 0.1
