    - Class: rviz/Group
      Displays:
        - Alpha: 1
          Class: rviz/RobotModel
          Collision Enabled: false
          Enabled: true
          Links:
            All Links Enabled: true
            Expand Joint Details: false
            Expand Link Details: false
            Expand Tree: false
            Link Tree Style: Links in Alphabetic Order
            base_body_link:
              Alpha: 1
              Show Axes: false
              Show Trail: false
              Value: true
            base_link_ground:
              Alpha: 1
              Show Axes: false
              Show Trail: false
            computer_link:
              Alpha: 1
              Show Axes: false
              Show Trail: false
              Value: true
            front_laser_link:
              Alpha: 1
              Show Axes: false
              Show Trail: false
              Value: true
            left_front_wheel_link:
              Alpha: 1
              Show Axes: false
              Show Trail: false
              Value: true
            left_rear_wheel_link:
              Alpha: 1
              Show Axes: false
              Show Trail: false
              Value: true
            right_front_wheel_link:
              Alpha: 1
              Show Axes: false
              Show Trail: false
              Value: true
            right_rear_wheel_link:
              Alpha: 1
              Show Axes: false
              Show Trail: false
              Value: true
          Name: Robot Model
          Robot Description: robot_{id}/robot_description
          TF Prefix: robot_{id}
          Update Interval: 0
          Value: true
          Visual Enabled: true
        - Alpha: 1
          Autocompute Intensity Bounds: true
          Autocompute Value Bounds:
            Max Value: 0.230000004
            Min Value: 0.230000004
            Value: true
          Axis: Z
          Channel Name: intensity
          Class: rviz/LaserScan
          Color: {r}; {g}; {b}
          Color Transformer: FlatColor
          Decay Time: 0
          Enabled: true
          Invert Rainbow: false
          Max Color: 255; 255; 255
          Max Intensity: 999999
          Min Color: 0; 0; 0
          Min Intensity: 0
          Name: LaserScan
          Position Transformer: XYZ
          Queue Size: 10
          Selectable: true
          Size (Pixels): 3
          Size (m): 0.0500000007
          Style: Squares
          Topic: /robot_{id}/scan
          Unreliable: false
          Use Fixed Frame: true
          Use rainbow: true
          Value: true
        - Alpha: 0.5
          Class: rviz/Map
          Color Scheme: costmap
          Draw Behind: true
          Enabled: false
          Name: Global Costmap
          Topic: /robot_{id}_move_base/global_costmap/costmap
          Unreliable: false
          Use Timestamp: false
          Value: false
        - Alpha: 0.699999988
          Class: rviz/Map
          Color Scheme: costmap
          Draw Behind: true
          Enabled: false
          Name: Local costmap
          Topic: /robot_{id}_move_base/local_costmap/costmap
          Unreliable: false
          Use Timestamp: false
          Value: false
        - Alpha: 1
          Arrow Length: 0.300000012
          Axes Length: 0.300000012
          Axes Radius: 0.00999999978
          Class: rviz/PoseArray
          Color: 255; 25; 0
          Enabled: true
          Head Length: 0.0700000003
          Head Radius: 0.0299999993
          Name: AmclPoseArray
          Shaft Length: 0.230000004
          Shaft Radius: 0.00999999978
          Shape: Arrow (Flat)
          Topic: /robot_{id}_amcl/particlecloud
          Unreliable: false
          Value: true
        - Alpha: 1
          Axes Length: 1
          Axes Radius: 0.100000001
          Class: rviz/PoseWithCovariance
          Color: 255; 25; 0
          Covariance:
            Orientation:
              Alpha: 0.5
              Color: 255; 255; 127
              Color Style: Unique
              Frame: Local
              Offset: 1
              Scale: 1
              Value: true
            Position:
              Alpha: 0.300000012
              Color: 204; 51; 204
              Scale: 1
              Value: true
            Value: true
          Enabled: false
          Head Length: 0.300000012
          Head Radius: 0.100000001
          Name: AmclPoseWithCovariance
          Shaft Length: 1
          Shaft Radius: 0.0500000007
          Shape: Arrow
          Topic: /robot_{id}_amcl/pose
          Unreliable: false
          Value: false
        - Alpha: 1
          Buffer Length: 1
          Class: rviz/Path
          Color: 25; 255; 0
          Enabled: true
          Head Diameter: 0.300000012
          Head Length: 0.200000003
          Length: 0.300000012
          Line Style: Lines
          Line Width: 0.0299999993
          Name: GlobalPath
          Offset:
            X: 0
            Y: 0
            Z: 0
          Pose Color: 255; 85; 255
          Pose Style: None
          Radius: 0.0299999993
          Shaft Diameter: 0.100000001
          Shaft Length: 0.100000001
          Topic: /robot_{id}_move_base/NavfnROS/plan
          Unreliable: false
          Value: true
        - Alpha: 1
          Buffer Length: 1
          Class: rviz/Path
          Color: 255; 0; 0
          Enabled: true
          Head Diameter: 0.300000012
          Head Length: 0.200000003
          Length: 0.300000012
          Line Style: Lines
          Line Width: 0.0299999993
          Name: DwaLocalPath
          Offset:
            X: 0
            Y: 0
            Z: 0
          Pose Color: 255; 85; 255
          Pose Style: None
          Radius: 0.0299999993
          Shaft Diameter: 0.100000001
          Shaft Length: 0.100000001
          Topic: /robot_{id}_move_base/TrajectoryPlannerROS/local_plan
          Unreliable: false
          Value: true
        - Alpha: 1
          Buffer Length: 1
          Class: rviz/Path
          Color: 255; 0; 0
          Enabled: true
          Head Diameter: 0.300000012
          Head Length: 0.200000003
          Length: 0.300000012
          Line Style: Lines
          Line Width: 0.0299999993
          Name: TebLocalPath
          Offset:
            X: 0
            Y: 0
            Z: 0
          Pose Color: 255; 85; 255
          Pose Style: None
          Radius: 0.0299999993
          Shaft Diameter: 0.100000001
          Shaft Length: 0.100000001
          Topic: /robot_{id}_move_base/TebLocalPlannerROS/local_plan
          Unreliable: false
          Value: true
      Enabled: true
      Name: Robot-{id}
